# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: simulation.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='simulation.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=b'\n\x10simulation.proto\"O\n\x06Person\x12\n\n\x02id\x18\x01 \x01(\t\x12\r\n\x05state\x18\x02 \x01(\t\x12\x16\n\x0einfection_date\x18\x03 \x01(\t\x12\x12\n\ndeath_date\x18\x04 \x01(\t\"1\n\nPopulation\x12\n\n\x02id\x18\x01 \x01(\t\x12\x17\n\x06people\x18\x02 \x03(\x0b\x32\x07.Person\"1\n\x0f\x43onnectionsList\x12\n\n\x02id\x18\x01 \x01(\t\x12\x12\n\nconnection\x18\x02 \x03(\t\"0\n\x07Network\x12%\n\x0b\x63onnections\x18\x01 \x03(\x0b\x32\x10.ConnectionsList\">\n\x0fTemporalNetwork\x12\x10\n\x08timestep\x18\x01 \x03(\t\x12\x19\n\x07network\x18\x02 \x03(\x0b\x32\x08.Network\"\\\n\x12SimulationTimeline\x12\n\n\x02id\x18\x01 \x01(\t\x12\x1f\n\npopulation\x18\x02 \x03(\x0b\x32\x0b.Population\x12\x19\n\x07network\x18\x03 \x03(\x0b\x32\x08.Networkb\x06proto3'
)




_PERSON = _descriptor.Descriptor(
  name='Person',
  full_name='Person',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='Person.id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='state', full_name='Person.state', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='infection_date', full_name='Person.infection_date', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='death_date', full_name='Person.death_date', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=20,
  serialized_end=99,
)


_POPULATION = _descriptor.Descriptor(
  name='Population',
  full_name='Population',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='Population.id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='people', full_name='Population.people', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=101,
  serialized_end=150,
)


_CONNECTIONSLIST = _descriptor.Descriptor(
  name='ConnectionsList',
  full_name='ConnectionsList',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='ConnectionsList.id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='connection', full_name='ConnectionsList.connection', index=1,
      number=2, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=152,
  serialized_end=201,
)


_NETWORK = _descriptor.Descriptor(
  name='Network',
  full_name='Network',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='connections', full_name='Network.connections', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=203,
  serialized_end=251,
)


_TEMPORALNETWORK = _descriptor.Descriptor(
  name='TemporalNetwork',
  full_name='TemporalNetwork',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='timestep', full_name='TemporalNetwork.timestep', index=0,
      number=1, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='network', full_name='TemporalNetwork.network', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=253,
  serialized_end=315,
)


_SIMULATIONTIMELINE = _descriptor.Descriptor(
  name='SimulationTimeline',
  full_name='SimulationTimeline',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='SimulationTimeline.id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='population', full_name='SimulationTimeline.population', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='network', full_name='SimulationTimeline.network', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=317,
  serialized_end=409,
)

_POPULATION.fields_by_name['people'].message_type = _PERSON
_NETWORK.fields_by_name['connections'].message_type = _CONNECTIONSLIST
_TEMPORALNETWORK.fields_by_name['network'].message_type = _NETWORK
_SIMULATIONTIMELINE.fields_by_name['population'].message_type = _POPULATION
_SIMULATIONTIMELINE.fields_by_name['network'].message_type = _NETWORK
DESCRIPTOR.message_types_by_name['Person'] = _PERSON
DESCRIPTOR.message_types_by_name['Population'] = _POPULATION
DESCRIPTOR.message_types_by_name['ConnectionsList'] = _CONNECTIONSLIST
DESCRIPTOR.message_types_by_name['Network'] = _NETWORK
DESCRIPTOR.message_types_by_name['TemporalNetwork'] = _TEMPORALNETWORK
DESCRIPTOR.message_types_by_name['SimulationTimeline'] = _SIMULATIONTIMELINE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Person = _reflection.GeneratedProtocolMessageType('Person', (_message.Message,), {
  'DESCRIPTOR' : _PERSON,
  '__module__' : 'simulation_pb2'
  # @@protoc_insertion_point(class_scope:Person)
  })
_sym_db.RegisterMessage(Person)

Population = _reflection.GeneratedProtocolMessageType('Population', (_message.Message,), {
  'DESCRIPTOR' : _POPULATION,
  '__module__' : 'simulation_pb2'
  # @@protoc_insertion_point(class_scope:Population)
  })
_sym_db.RegisterMessage(Population)

ConnectionsList = _reflection.GeneratedProtocolMessageType('ConnectionsList', (_message.Message,), {
  'DESCRIPTOR' : _CONNECTIONSLIST,
  '__module__' : 'simulation_pb2'
  # @@protoc_insertion_point(class_scope:ConnectionsList)
  })
_sym_db.RegisterMessage(ConnectionsList)

Network = _reflection.GeneratedProtocolMessageType('Network', (_message.Message,), {
  'DESCRIPTOR' : _NETWORK,
  '__module__' : 'simulation_pb2'
  # @@protoc_insertion_point(class_scope:Network)
  })
_sym_db.RegisterMessage(Network)

TemporalNetwork = _reflection.GeneratedProtocolMessageType('TemporalNetwork', (_message.Message,), {
  'DESCRIPTOR' : _TEMPORALNETWORK,
  '__module__' : 'simulation_pb2'
  # @@protoc_insertion_point(class_scope:TemporalNetwork)
  })
_sym_db.RegisterMessage(TemporalNetwork)

SimulationTimeline = _reflection.GeneratedProtocolMessageType('SimulationTimeline', (_message.Message,), {
  'DESCRIPTOR' : _SIMULATIONTIMELINE,
  '__module__' : 'simulation_pb2'
  # @@protoc_insertion_point(class_scope:SimulationTimeline)
  })
_sym_db.RegisterMessage(SimulationTimeline)


# @@protoc_insertion_point(module_scope)
